### ISSUE TITLE
run-in-xephyr.sh: NIX_PATH: unbound variable 

### ISSUE THREAD

**Issue by xrvdg** [xmonad/xmonad-testing#11]
I get this error: `NIX_PATH: unbound variable` when I try to execute `./bin/run-in-xephyr.sh`.

I have tracked down the issue to the `-u` flag in the shebang (`#!/bin/sh -eu`). But why is this flag necessary?

The [POSIX manual](http://pubs.opengroup.org/onlinepubs/9699919799/) states:
> -u
    When the shell tries to expand an unset parameter other than the '@' and '*' special parameters, it shall write a message to standard error and the expansion shall fail with the consequences specified in Consequences of Shell Errors.

Is there a reason why execution should fail when `NIX_PATH` is not set? Or can we drop the `-u` flag? `run-in-xephyr.sh` seems to run fine without it.

**Comment by pjones** [comment]
Thank you for reporting this.  The `-u` option is useful for finding subtle bugs in shell scripts.  This has been fixed.
