### ISSUE TITLE
XMonad Build Scripts cause compilation failures.

### ISSUE THREAD

**Issue by crocket** [xmonad/xmonad-testing#8]
build script examples use `mv -u` which breaks subsequence builds
because previous runs displaced the build result.

`cp -u` fails because the destination is already being used by
xmonad process.

geekosaur suggested `rm -f $TARGET.old && mv $TARGET $TARGET.old && mv $new $TARGET`.
I prefer `rm -f $TARGET.old && mv $TARGET $TARGET.old && cp $new $TARGET`, but these commands update xmonad binary even when there is no change.

We need something better.

**Comment by mgsloan** [comment]
Creating a hardlink works well and is very fast - see my updates to the stack build script [here](https://github.com/xmonad/xmonad-testing/pull/12/files) (not yet merged)

**Comment by byorgey** [comment]
I believe this can be closed now that @mgsloan 's PR is merged?  If not feel free to reopen.
